version: "3.9"
services:
  botnet:
    container_name: frt
    image: frt
    build: .
    restart: always
    volumes:
      - ./data:/data
    ports:
      - '8080:80'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://root:secret_password@postgres/data

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: data
      POSTGRES_PASSWORD: secret_password
      POSTGRES_USER: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
